name: Build and deploy compose-web sample to GitHub pages

on:
    push:
        branches: [ "main" ]
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   name: Set up JDK 11
                uses: actions/setup-java@v3
                with:
                    java-version: '11'
                    distribution: 'temurin'
                    cache: 'gradle'

            -   name: Setup Gradle
                uses: gradle/gradle-build-action@v2

            -   uses: actions/checkout@v3
                with:
                    path: koalaplot-samples

            -   name: Validate Gradle wrapper
                uses: gradle/wrapper-validation-action@v1

            -   name: Checkout koalaplot-core
                uses: actions/checkout@v3
                with:
                    repository: koalaplot/koalaplot-core
                    path: koalaplot-core

            -   name: Publish koalaplot-core to Maven Local
                uses: gradle/gradle-build-action@v2
                with:
                    arguments: check publishToMavenLocal
                    build-root-directory: koalaplot-core

            -   name: Build koalaplot-samples
                uses: gradle/gradle-build-action@v2
                with:
                    arguments: build
                    build-root-directory: koalaplot-samples

            # jsBrowserWebpack in one step doesn't put skiko.wasm or skio.js in the distributions directory
            -   name: Build koalaplot-samples
                uses: gradle/gradle-build-action@v2
                with:
                    arguments: jsBrowserWebpack
                    build-root-directory: koalaplot-samples
